#!/usr/bin/env lua

local filename = "isr_stubs.h"
local max_limit = 255
local file = io.open(filename, "w")

file:write("#pragma once\n\n")
file:write("// This file is autogenerated by Meta/x86_64-tools/generate_isr_stubs.lua\n\n")
file:write('extern "C" {\n\n')

for j = 0, max_limit do
	file:write(string.format("    void isr%d();\n", j))
end

file:write("}\n")

file:write(string.format("static void (*g_isr_stubs[%d])() = {\n", max_limit + 1))
for j = 0, max_limit do
	local sep = (j < max_limit) and "," or ""
	file:write(string.format("    isr%d%s\n", j, sep))
end
file:write("};\n\n")

file:close()
print("Gerado: " .. filename)
