#!/usr/bin/env bash

echo "#pragma once"
echo
echo "// This code is Auto-generated by Meta/load_isr"
echo
echo "// Auto-generated ISR stubs"
for i in $(seq 0 255); do
	echo "extern \"C\" void isr_stub_$i();"
done

echo ""
echo "using ISRHandler = void(*)();"
echo "constexpr ISRHandler isr_stubs[256] = {"
for i in $(seq 0 255); do
	if [ "$i" -lt 255 ]; then
		echo "    isr_stub_$i,"
	else
		echo "    isr_stub_$i"
	fi
done
echo "};"
