#!/usr/bin/env bash

echo "#pragma once"
echo
echo "// This code is Auto-generated by Meta/load_isr"
echo
echo "// Auto-generated ISR stubs"
echo
for i in $(seq 0 255); do
	echo "// extern \"C\" void isr_stub_$i();"
done
