#pragma once

#include <LibFK/Types/types.h>

enum SyscallNumber : uint64_t {
    SYS_READ = 0,
    SYS_WRITE = 1,
    SYS_OPEN = 2,
    SYS_CLOSE = 3,
    SYS_STAT = 4,
    SYS_FSTAT = 5,
    SYS_LSTAT = 6,
    SYS_LSEEK = 8,
    SYS_MMAP = 9,
    SYS_MUNMAP = 11,
    SYS_BRK = 12,
    SYS_SIGACTION = 13,
    SYS_SIGPROCMASK = 14,
    SYS_SIGRETURN = 15,
    SYS_RT_SIGSUSPEND = 130,
    SYS_IOCTL = 16,
    SYS_WRITEV = 20,
    SYS_YIELD = 24,
    SYS_NANOSLEEP = 35,
    SYS_GETTIMEOFDAY = 96,
    SYS_GETPID = 39,
    SYS_DUP2 = 33,
    SYS_SOCKET = 41,
    SYS_CONNECT = 42,
    SYS_ACCEPT = 43,
    SYS_BIND = 49,
    SYS_LISTEN = 50,
    SYS_FORK = 57,
    SYS_EXECVE = 59,
    SYS_EXIT = 60,
    SYS_WAIT4 = 61,
    SYS_KILL = 62,
    SYS_UNAME = 63,
    SYS_FCNTL = 72,
    SYS_READDIR = 78, // getdents (32-bit/old)
    SYS_GETDENTS64 = 217,
    SYS_GETCWD = 79,
    SYS_CHDIR = 80,
    SYS_MKDIR = 83,
    SYS_GETUID = 102,
    SYS_GETGID = 104,
    SYS_GETEUID = 107,
    SYS_GETEGID = 108,
    SYS_GETPGRP = 111,
    SYS_GETPPID = 110,
    SYS_ARCH_PRCTL = 158,
    SYS_SET_TID_ADDRESS = 218,
    SYS_MOUNT = 165,
    SYS_UMOUNT2 = 166,
    SYS_GETTID = 186,
    SYS_CLOCK_GETTIME = 228,
    SYS_EXIT_GROUP = 231,
    SYS_IPC_SEND = 400,
    SYS_IPC_RECEIVE = 401,
    SYS_IPC_CALL = 402,
    SYS_MAX = 512
};
