name: Run C Unit Tests with Xmake

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash
        export PATH=$HOME/.xmake/bin:$PATH
        source ~/.xmake/profile
        xmake --version

    - name: Build and run tests
      run: |
        export PATH=$HOME/.xmake/bin:$PATH
        xmake -bv Test
        xmake run Test
