name: Codacy Security Scan

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: '26 8 * * 6'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Codacy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Make SARIF unique
        run: |
          python3 - <<'EOF'
          import json, os

          input_file = "results.sarif"
          output_file = "results_unique.sarif"

          with open(input_file, "r", encoding="utf-8") as f:
              data = json.load(f)

          unique_id = os.environ.get("GITHUB_RUN_ID", "manual")

          for run in data.get("runs", []):
              driver = run.get("tool", {}).get("driver", {})

              # Nome único
              if isinstance(driver.get("name"), str):
                  driver["name"] = f"{driver['name']}-{unique_id}"
              else:
                  driver["name"] = f"Tool-{unique_id}"

              # fullName único
              if isinstance(driver.get("fullName"), str):
                  driver["fullName"] = f"{driver['fullName']} (Run {unique_id})"
              else:
                  driver["fullName"] = driver.get("name", f"Tool-{unique_id}")

          # Salva em arquivo novo para evitar PermissionError
          with open(output_file, "w", encoding="utf-8") as f:
              json.dump(data, f, indent=2)
          EOF

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results_unique.sarif
          category: "Codacy Security Scan-${{ github.ref_name }}"
